project_id = "zzegeatnzvoqhgffqfln"

[functions.lookup-term]
verify_jwt = false

[functions.get-active-sources]
verify_jwt = false

[functions.generate-slang]
verify_jwt = false

[functions.create-manual-slang]
verify_jwt = true

[functions.manage-favorites]
verify_jwt = true

[functions.vote-creation]
verify_jwt = true

[functions.user-history]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.log-share]
verify_jwt = true

[functions.monitor-shared-slang]
verify_jwt = true

[functions.update-leaderboards]
verify_jwt = false