project_id = "zzegeatnzvoqhgffqfln"

[functions.lookup-term]
verify_jwt = false

[functions.generate-slang]
verify_jwt = false

[functions.manage-favorites]
verify_jwt = true

[functions.vote-creation]
verify_jwt = true

[functions.user-history]
verify_jwt = true